spring.application.name=LinkHammer


spring.datasource.url=jdbc:mysql://localhost:3306/LinkHammer
spring.datasource.username=root
spring.datasource.password=934349
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG


jwt.secret=80a94912aa82b6ec4660ce2ff42e884a3bdb84ba20056379e1237cb4d87b9cde
jwt.expiration=178200000




spring.ai.openai.api-key=AIzaSyDg5stWmKqwOBBYlRCVSPzdQPvJ6oPeEW0
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-2.0-flash